# Generated by Django 4.0.3 on 2022-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='memory',
            old_name='book',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateField(verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateField(verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='text',
            field=models.TextField(verbose_name='感想'),
        ),
    ]
